name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  basic-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2

      - name: run basic test
        shell: bash
        run: |
          sudo bash build.sh init
          echo "begin test..."
          python3 test/case/miniob_test.py --test-cases=basic | tail -1 | grep "basic is success"

  sysbench-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2

      - name: install sysbench
        shell: bash
        run: |
          curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh -o script.deb.sh
          sudo bash script.deb.sh
          sudo apt -y install sysbench

      - name: start server
        shell: bash
        run: |
          sudo bash build.sh init
          bash build.sh -DCONCURRENCY
          ./build_debug/bin/observer -s miniob.sock -f etc/observer.ini -P mysql -t mvcc &

      - name: sysbench test
        shell: bash
        run: |
          cd test/sysbench
          sysbench --mysql-socket=../../build_debug/miniob.sock --threads=10 miniob_insert prepare
          sysbench --mysql-socket=../../build_debug/miniob.sock --threads=10 miniob_insert run
